### ISSUE TITLE
Making a new order extraction map (from the flat fields) appears to now be saved in the working directory instead of "custommap"

### ISSUE THREAD

**Issue by leejjoon** [igrins/plp#1]
The original bug report is from Kyle Kaplan.

---

Making a new order extraction map (from the flat fields) appears to now be saved in the working directory instead of "custommap" in the old version of the PLP.
-In PL_Display.py....
-Commented out the declaration "self.reducepath = './custommap/'"
-Replaced every instance of "custompath" with "self.reducepath"

**Comment by kfkaplan** [comment]
@leejjoon Has this issue been fixed? If so, we can close it.

**Comment by kfkaplan** [comment]
PL_Display.py no longer seems to exist and I am sure this was solved long ago, so I am going to close this issue.  If needed, we can reopen it.
