### ISSUE TITLE
Allow for indata *.fits files to be compressed with gzip

### ISSUE THREAD

**Issue by henryroe** [igrins/plp#13]
FITS files typically compress nicely & to save disk space I would like to be able to store my raw IGRINS data in gzip'd form.  (I usually do a `gzip --best *.fits` in my raw data directories.)

When reading in a fits file, ideally igrins-plp should seamlessly read either a gzip'd or non-gzip'd file.

I've a simple fix to enable this behavior that I will submit as a pull request.  Basically, I've written a simple wrapper to the fits routines and then replace a bunch of `import` statements throughout the rest of the code to import my wrapper rather than astropy.io.fits.  I think it's self explanatory.

**Comment by kfkaplan** [comment]
The latest version of the PLP (qlook and flexure branches currently) can read in .gz and .bz2 compressed fits files in indata.  I am going to consider this issue solved.
