### ISSUE TITLE
Missing library get_destripe_mask?

### ISSUE THREAD

**Issue by kfkaplan** [igrins/plp#18]
I find the following issue when trying to run the wavelength solution parts of the PLP thar or sky-wvlsol in the latest "fix numpy" issue of the PLP:

  File "/Volumes/IGRINS_Data/plp/recipes/libs/image_combine.py", line 14, in make_combined_image_sky
    from get_destripe_mask import get_destripe_mask
ImportError: No module named get_destripe_mask

From what I can tell the library image_combine.py is trying to import the library get_destripe_mask but get_destripe_mask.py does not appear to exist anywhere.  I suspect it just needs to be added to the github repository.

-Kyle

**Comment by leejjoon** [comment]
Thanks.
The file is added with commit 05f4217 in the "issue_numpy" branch.
Let me know if it still fails.

**Comment by kfkaplan** [comment]
That seems to have fixed that issue but now I have the following issue:

  File "/Volumes/IGRINS_Data/plp/recipes/libs/get_destripe_mask.py", line 7, in get_pix_mask
    "hotpix_mask")
  File "/Volumes/IGRINS_Data/plp/recipes/libs/cal_db.py", line 225, in load_resource_for
    resource_basename, item_desc = self.query_resource_for(basename, resource_type)
  File "/Volumes/IGRINS_Data/plp/recipes/libs/cal_db.py", line 216, in query_resource_for
    raise e  # it would be good if we can modify the message
ValueError: too many values to unpack

**Comment by leejjoon** [comment]
I am afraid I cannot reproduce this error (it works fine with me).

The lines where the exception is raised does not match the current code base. What branch are you on?

**Comment by kfkaplan** [comment]
Yes you were right, I must have been using a different version of the PLP.  I re-downloaded and installed the "issue_numpy" branch and it worked.
