### ISSUE TITLE
When reducing the standards and science targets, saving .png files causes an error 

### ISSUE THREAD

**Issue by leejjoon** [igrins/plp#2]
Original report from Kyle Kaplan.

---

When reducing the standards and science targets, saving .png files causes an error related to "fontsize=XXX" when defining a legend for a plot such as in
"p1.legend(loc='upper left',bbox_to_anchor=(1,1), fontsize=11)"
According to http://stackoverflow.com/questions/18920712/matplotlib-legend-fontsize:
   Setting the font size via kwarg does not work because you are using an antiquated version of matplotlib. The error it is giving you,
   TypeError: **init**() got an unexpected keyword argument 'fontsize' means that fontsize is not a valid keyword argument of the **init** function.  
-Solution is to remove "fontsize=11" from the three instances in PL_Display.py like...
    p1.legend(loc='upper left',bbox_to_anchor=(1,1), fontsize=11)
 is replaced with...
    p1.legend(loc='upper left',bbox_to_anchor=(1,1))

**Comment by kfkaplan** [comment]
I'm almost certain this issue has been fixed.  I am closing it.
