### ISSUE TITLE
Out of date packages in the "How to run pipeline" page 

### ISSUE THREAD

**Issue by hwihyun** [igrins/plp#20]
Hello JJ,

The current version of PLP requires stsci.image v2.1 but it doesn't run with that version any more. 
![image](https://user-images.githubusercontent.com/8321492/92181809-27a56d00-ee18-11ea-8a2c-12c7cba4c24c.png)

I just updated it to stsci.image 2.3 and it is running fine now. 

Thanks,
Hwi

**Comment by hwihyun** [comment]
Same issue with 
numpy 1.8.2. --> v1.16.6 for "nanmedian",
pandas 0.14.1 --> v0.24.2 for "orient" argument in df.to_dict method.

**Comment by kfkaplan** [comment]
The installation instructions have been rewritten and no longer include a recommended version number for the packages.  Currently you should be able use the latest version of each package and everything should work fine, except for one thing, the PLP is incompatible with python 3.12 currently, so you should use python 3.11 or below.  If you find any further incompatibilities, please reopen this issue.
