### ISSUE TITLE
1D extraction in the .spec.fits file for EXTENDED-ONOFF sources appears to assume nodding on slit

### ISSUE THREAD

**Issue by kfkaplan** [igrins/plp#24]
I have noticed that for EXTENDED-ONOFF targets, for the `qlook` (and by extension `flexure`) branches, that the 1D spectrum in the .spec.fits files appears to not be extracting the spectrum correctly and the extraction hovers around zero counts.  I suspect the 1D extraction is incorrectly assuming ABBA nodding of the target on slit.  For comparison, summing along the slit axis in the .spec2d.fits files results in the correct 1D extraction.  See the attached plot of an H band order from an emission line nebula where summing the order found in the .spec2d.fits file gives the correct extraction for the extended object while the 1D spectrum found in the .spec.fits file appears to be ABBA extracted.
<img width="1082" alt="Screenshot 2023-09-05 at 5 58 59 PM" src="https://github.com/igrins/plp/assets/8240156/89c99b7c-0ebf-406d-84ec-92e1a152f779">

Targets labeled STELLAR-AB or A0V-AB are correctly extracted in 1D so for point sources nodded on the slit, there is no issue here, this only applies to EXTENDED-ONOFF.

**Comment by leejjoon** [comment]
Thanks. I have pushed the fix for this.  Please try the most recent qlook branch and let me know.

**Comment by kfkaplan** [comment]
I don't see the commit on the qlook branch.  Can you push to the remote repo?

**Comment by leejjoon** [comment]
My apology. I pushed it but with a different branch name. The change was also applied to the qlook branch. So, please check it again.

**Comment by kfkaplan** [comment]
Okay I merged the new commits in the `qlook` branch with the `flexure` branch and reran a night.  The extracted 1D spectra for extended-onoff now look nearly identical compared to nansum collapsing the 2D spectrum (as seen in the example).  I consider this issue solved and will close it.
<img width="1492" alt="Screenshot 2023-10-17 at 1 30 50 PM" src="https://github.com/igrins/plp/assets/8240156/0199fb67-048c-4cef-84ed-20871b3c8e3c">
