### ISSUE TITLE
Difference in Continuum Shape of New and Old PIpeline

### ISSUE THREAD

**Issue by ericasaw** [igrins/plp#26]
Here is an example of what the continuum looks like in the new pipeline for a .spec_a0v.fits file

![bad_cont](https://github.com/igrins/plp/assets/50722189/6f0bdad2-71c2-4d87-8de1-c176313b0dad)

This is what the continuum looks like in the old pipeline
![old_pipe](https://github.com/igrins/plp/assets/50722189/ab32c4d4-2155-4a11-acbe-2bc3fce8c81f)

We found that the new version of the pipeline is flattening the Vega spectrum (but we are unsure why this was implemented). Kyle just pushed a fix for this to the [reimplement_cr_reject](https://github.com/igrins/plp/tree/reimplement_cr_reject) branch that removes the flattening. 

This is what the continuum looks like for this branch of the pipeline with this fix
![new_pipe](https://github.com/igrins/plp/assets/50722189/fad6b11e-5097-4f99-bed2-1a304d87332c)

Additionally Kyle brought up the slight increase in the flux in the new pipeline (Issue #25; < 2%). We posited that as long as the A0 and the target were reduced with the same pipeline this flux difference wouldn't matter in the spec_a0v.fits files since the ratio between the target and standard would stay the same. Just want to note that things work out like we expected. Here is a single order in the old pipeline, blue, and the new pipeline (non-flattened Vega), orange, and we can see the flux doesnt have any consistent offset which is what we had hoped for
![good_norm](https://github.com/igrins/plp/assets/50722189/430b0078-cd8e-4a9c-8e31-bbc427edf375)

I'm basically raising this issue to document the issue occurring in the new pipeline and to ask @leejjoon if he would be upset if we turned the Vega flattening off in the next release.

**Comment by kfkaplan** [comment]
The bottom plot also nicely shows how the new flexure correction is leading to better telluric correction.
